#!/usr/bin/perl -w
# GPLv3 Matija Nalis <mnalis-perl@axe.tomsoft.hr> 2014-02-06
# call multiple S.M.A.R.T. plugins and check status
# call for all hard disks in system

# FIXME vidi dodatne atribute na http://en.wikipedia.org/wiki/S.M.A.R.T.
  

use strict;

my $check_ide_smart_cmd = '/usr/lib/nagios/plugins/check_ide_smart';
my $check_smart_cmd = '/root/nagios_moj_smart/check_smart';	# FIXME path. autofind?
my $check_smartmon_cmd = '/root/nagios_moj_smart/check_smartmon';	# FIXME path. autofind?

my $DEBUG = 1;

my @exit_disk = ();
my @exit_value = ();
my @exit_code = ();
my @exit_txt = ();
my @exit_perf = ();

# execute command if present
sub exec_cmd
{
    my $cmd = shift;
    my $args = join (' ', @_);
    return `$cmd $args`;
}

# executes command and handle output
sub handle_cmd
{
    my $disk = $_[$#_];	# FIXME kludge, get disk - assume always last parameter passed
    
    my $output = exec_cmd (@_);
    my $exit_sig = $? & 127;
    my $exit_code = $? >> 8;
    
    if ($exit_sig) {
       $exit_code = 3; $output = "UNKNOWN: exit_sig=$exit_sig " . $output;
    }
    
    
    my $_code;
    my $_msg;
    my $_perf;
    $DEBUG > 2 && print "za cmd=" . join(' ',@_) . ", disk=$disk: \n";
#    print "\tfull=$output, code=$?\n";
    if ($output =~ /^(OK|CRITICAL|WARNING|UNKNOWN)\s*[-:]?\s+(.*?)(\|(.*))?$/) {
         $_code = $1;
         $_msg = $2;
         $_perf = defined($4) ? $4 : '';
         $DEBUG > 2 && print "\tnasao output: code=$_code, msg=$_msg, perf=$_perf\n";
    } else {
         $exit_code = 3;
         $_code = 'UNKNOWN';
         $_msg = "unknown output: $output";
         $_perf = '';
         $DEBUG > 2 && print "$_msg\n";
    }

    push @exit_disk, $disk;
    push @exit_value, $exit_code;
    push @exit_code, $_code;
    push @exit_txt, $_msg;
    push @exit_perf, $_perf;
}

# FIXME - add argumente modul i za exclude diskova

{
my @disks = glob("/dev/[hs]d*[a-z]");
# FIXME kludge delme
@disks = qw (/dev/sdb /dev/sda /dev/sdg /dev/sdc);


foreach my $disk (@disks) {
    handle_cmd ($check_ide_smart_cmd, '-1', '-n', '-d', $disk);
    handle_cmd ($check_smart_cmd, '-i', 'ata', '-d', $disk);
    handle_cmd ($check_smartmon_cmd, '-d', $disk);
}
}

# FIXME izvuci iz arraya i slozi vars

if ($DEBUG > 1) {
  print "\n\n\n";
  print "disks = " . join (", ", @exit_disk) . "\n\n";
  print "values = " . join (", ", @exit_value) . "\n\n";
  print "code = " . join (", ", @exit_code) . "\n\n";
  print "txt = " . join (", ", @exit_txt) . "\n\n";
  print "perf = " . join (", ", @exit_perf) . "\n\n";
}


my $max_exit_level = 0;
my $output_code = '';
my $last_err = 'All OK.';
my $err_count = 0;
my $output_text = '';
my $perfdata = '';

my $last_disk = $exit_disk[0];
my $last_msg = '';
my $last_perf = '';

my @all = ();

# check if we have new maximum value 
# note that it is more complicated than simple integer check, as UNKNOWN state is not worst!
#
# rating is (from better to worse): (0=OK, 3=UNKNOWN, 1=WARNING, 2=CRITICAL)
# 
sub is_new_max
{
    my ($cur, $old) = @_;
    
    $DEBUG > 2 && print "check $old <=> $cur\n";
    die "invalid return value $old => $cur" if ($old > 3) or ($old < 0) or ($cur > 3) or ($cur < 0);
    
    if ($old == 0) { return 1 }			# if we were OK before, anything else is more important!
    if ($old == 2) { return 0 }			# if we were CRITICAL before, nothing else could be more important
    if ($old == 1) { return ($cur == 2) }	# if we were WARNING before, only CRITICAL is more important, others are not
    if ($old == 3) { return ($cur != 0) }	# if we were UNKNOWN before, only OK is less important
}

# consolidate disk data
sub consolidate {
    my ($x) = @_;
    $DEBUG > 1 && print "consolidating at $x, last_disk=$last_disk\n";
    $DEBUG > 1 && print "full msg=$last_msg\n";
    $DEBUG > 1 && print "full perf=$last_perf\n\n";

    $last_msg =~ s/\n/, /g;
    push @all, { disk=> $last_disk, msg => $last_msg, perf => $last_perf };
    
    $last_msg = '';
    $last_perf = '';
    $last_disk = $exit_disk[$x];
}

# consolidate all checks (group by same disk)
for my $x (0 .. $#exit_disk) {
    consolidate($x) if ($exit_disk[$x] ne $last_disk);
    if (is_new_max($exit_value[$x], $max_exit_level)) {	# final result is worst result we've had (0=OK, 3=UNKNOWN, 1=WARNING, 2=CRITICAL);
        $max_exit_level = $exit_value[$x];
        $output_code = $exit_code[$x];
    }
    if ($exit_value[$x]) {
        unless ($err_count++) {
            $last_err = "$err_count msgs, last= " . $exit_txt[$x];
            $last_err =~ s/\n/; /g;
        }
        $DEBUG > 1 && print "\t$err_count msgs, cur= " . $exit_txt[$x] . "\n";
    }
    $last_msg .= ($last_msg?', ':'') . $exit_txt[$x];
    $last_perf .= ($last_perf?' ':'') . $exit_perf[$x];
    $DEBUG > 1 && print "x=$x, " . $exit_disk[$x] . "\n";
}
consolidate($#exit_disk);


# join output for multiple disks if it is the same
my $prev_output = '';
my @prev_disks = ();
@all = sort {($a->{msg} cmp $b->{msg}) || $a->{disk} cmp $b->{disk} } @all;	# sort by output message (and disk)

# compresses list of /dev/sda, /dev/sdb, /dev/sdg into /dev/sd[abg] format
sub compress_disks
{
  return join(', ', @_);
}

# merge multiple messages for different disks
sub merge_msg
{
    return unless $prev_output;
    $output_text .= compress_disks(@prev_disks) . ": $prev_output\n";
    $DEBUG > 1 && print "merge_msg prev=$prev_output for disks " . join(', ', @prev_disks) . "\n";
    @prev_disks = ();
}

for my $x (0 .. $#all) {
    if ($prev_output ne $all[$x]->{msg}) { merge_msg() }
    $perfdata .= $all[$x]->{disk} . ': ' .  $all[$x]->{perf} . "\n";
    $DEBUG > 2 && print "x=$x, disk=" . $all[$x]->{disk} . ", msg=" . $all[$x]->{msg} . "\n";
    $DEBUG > 3 && print "x=$x, disk=" . $all[$x]->{disk} . ", perf=" . $all[$x]->{perf} . "\n";
    $prev_output = $all[$x]->{msg};
    push @prev_disks, $all[$x]->{disk};
}
merge_msg();
chomp($output_text);

#use Data::Dumper;
#print Dumper(\@all);

print "$output_code $last_err\n$output_text|$perfdata\n";
exit $max_exit_level;
