Document: check-multi-smart
Title: Debian check-multi-smart Manual
Author: <insert document author here>
Abstract: This manual describes what check-multi-smart is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/check-multi-smart/check-multi-smart.sgml.gz

Format: postscript
Files: /usr/share/doc/check-multi-smart/check-multi-smart.ps.gz

Format: text
Files: /usr/share/doc/check-multi-smart/check-multi-smart.text.gz

Format: HTML
Index: /usr/share/doc/check-multi-smart/html/index.html
Files: /usr/share/doc/check-multi-smart/html/*.html
